import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
import { teams } from './teams.js';

export const tasks = sqliteTable('tasks', {
  id: text('id').primaryKey(),
  teamId: text('team_id').notNull().references(() => teams.id),
  projectId: text('project_id'),
  parentId: text('parent_id'),
  goalId: text('goal_id'),
  title: text('title').notNull(),
  description: text('description'),
  status: text('status').notNull().default('backlog'),
  priority: text('priority').notNull().default('medium'),
  assigneeAgentId: text('assignee_agent_id'),
  assigneeUserId: text('assignee_user_id'),
  checkoutRunId: text('checkout_run_id'),
  executionLockedAt: integer('execution_locked_at'),
  taskNumber: integer('task_number'),
  identifier: text('identifier').unique(),
  originKind: text('origin_kind').notNull().default('manual'),
  originId: text('origin_id'),
  originRunId: text('origin_run_id'),
  requestDepth: integer('request_depth').notNull().default(0),
  billingCode: text('billing_code'),
  createdByAgentId: text('created_by_agent_id'),
  createdByUserId: text('created_by_user_id'),
  startedAt: integer('started_at'),
  completedAt: integer('completed_at'),
  cancelledAt: integer('cancelled_at'),
  hiddenAt: integer('hidden_at'),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, (table) => [
  index('tasks_team_status_idx').on(table.teamId, table.status),
  index('tasks_assignee_idx').on(table.teamId, table.assigneeAgentId, table.status),
  index('tasks_parent_idx').on(table.teamId, table.parentId),
  index('tasks_project_idx').on(table.teamId, table.projectId),
  index('tasks_origin_idx').on(table.teamId, table.originKind, table.originId),
]);
